spring.application.name=MedEase
server.port=8091

app.jwt.secret=mySecretKeyForJWTTokenGenerationThatIsAtLeast32CharactersLong
app.jwt.expiration-ms=86400000
spring.data.mongodb.uri=mongodb://localhost:27017/MedEase
