spring.application.name=MedEase
server.port=8091

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}
google.client.id=${GOOGLE_CLIENT_ID}

spring.mongodb.uri=${DB_URI}
spring.mongodb.database=MedEase


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
