spring.application.name=MedEase
server.port=8091

app.jwt.secret=k3rBa+Fd/Sff+5H6h0ADOX5TLA3AnPzbQ8BthUssIjAX0kPHYSXCbD5JthVfVinKcKai3Rk9s44IifBB3uC2Q
app.jwt.expiration-ms=86400000

spring.mongodb.uri=mongodb://localhost:27017/MedEase